import { Heart, FileText, Calendar, CircleCheckBig, X } from 'lucide-react';

export const COLUMNS = [
  {
    id: 'saved',
    label: 'Saved',
    icon: Heart,
    barColor: 'bg-[#294A73]',
    textColor: 'text-[#294A73]',
    badgeBg: 'bg-[#DCE8F3]',
    badgeText: 'text-[#294A73]',
    hoverBg: 'hover:bg-[#DCE8F3]',
    emptyText: 'No jobs in Saved',
    emptyHint: 'Save jobs you want to track here.',
  },
  {
    id: 'applied',
    label: 'Applied',
    icon: FileText,
    barColor: 'bg-[#18B8BC]',
    textColor: 'text-[#117D84]',
    badgeBg: 'bg-[#CEF2F1]',
    badgeText: 'text-[#117078]',
    hoverBg: 'hover:bg-[#CEF2F1]',
    emptyText: 'No jobs in Applied',
    emptyHint: 'Move jobs here once your application is sent.',
  },
  {
    id: 'interviewing',
    label: 'Interviewing',
    icon: Calendar,
    barColor: 'bg-[#4C8194]',
    textColor: 'text-[#23677C]',
    badgeBg: 'bg-[#D7EDF1]',
    badgeText: 'text-[#205D70]',
    hoverBg: 'hover:bg-[#D7EDF1]',
    emptyText: 'No jobs in Interviewing',
    emptyHint: 'Keep active interview processes organized here.',
  },
  {
    id: 'offered',
    label: 'Offered',
    icon: CircleCheckBig,
    barColor: 'bg-[#239C81]',
    textColor: 'text-[#177663]',
    badgeBg: 'bg-[#CDEEE4]',
    badgeText: 'text-[#146553]',
    hoverBg: 'hover:bg-[#CDEEE4]',
    emptyText: 'No jobs in Offered',
    emptyHint: 'Offers you receive will be collected here.',
  },
  {
    id: 'rejected',
    label: 'Rejected',
    icon: X,
    barColor: 'bg-[#C46A77]',
    textColor: 'text-[#A34C5A]',
    badgeBg: 'bg-[#F2DDE1]',
    badgeText: 'text-[#913F4D]',
    hoverBg: 'hover:bg-[#F2DDE1]',
    emptyText: 'No jobs in Rejected',
    emptyHint: 'Archive applications that did not move forward.',
  },
];
